# scikit-learn

***

10% A clear and concise overview of the scikit-learn Python library

***

20% Demonstrations of three interesting scikit-learn algorithms. You may choose
these yourself, based on what is covered in class or otherwise. Note that the
demonstrations are at your discretion – you may choose to have an overall spread
of examples across the library or pick a particular part that you find interesting.

***

10% Appropriate plots and other visualisations to enhance your notebook for viewers.

***

## Scikit-learn: Overview

***

## Code

***

In [1]:
import sklearn.datasets as datasets

In [2]:
iris = datasets.load_iris()

In [4]:
digits = datasets.load_digits()

In [6]:
print(digits.data)

[[ 0.  0.  5. ...  0.  0.  0.]
 [ 0.  0.  0. ... 10.  0.  0.]
 [ 0.  0.  0. ... 16.  9.  0.]
 ...
 [ 0.  0.  1. ...  6.  0.  0.]
 [ 0.  0.  2. ... 12.  0.  0.]
 [ 0.  0. 10. ... 12.  1.  0.]]


In [7]:
digits.target

array([0, 1, 2, ..., 8, 9, 8])

In [8]:
digits.images[0]

array([[ 0.,  0.,  5., 13.,  9.,  1.,  0.,  0.],
       [ 0.,  0., 13., 15., 10., 15.,  5.,  0.],
       [ 0.,  3., 15.,  2.,  0., 11.,  8.,  0.],
       [ 0.,  4., 12.,  0.,  0.,  8.,  8.,  0.],
       [ 0.,  5.,  8.,  0.,  0.,  9.,  8.,  0.],
       [ 0.,  4., 11.,  0.,  1., 12.,  7.,  0.],
       [ 0.,  2., 14.,  5., 10., 12.,  0.,  0.],
       [ 0.,  0.,  6., 13., 10.,  0.,  0.,  0.]])

In [9]:
import numpy as np

In [11]:
seed = 1234

In [13]:
rng = np.random.default_rng(seed = seed)

In [14]:
vals = rng.standard_normal(10)

In [15]:
vals

array([-1.60383681,  0.06409991,  0.7408913 ,  0.15261919,  0.86374389,
        2.91309922, -1.47882336,  0.94547297, -1.66613546,  0.34374458])

## References

***

[1].

[2].

[3].

[4].

***